---
output: 
  word_document:
    reference_docx: N:/Status_and_Trend_Reports/Report_Files/Report_Template.docx
    keep_md: yes
    toc: yes
    fig_caption: yes
    fig_width: 12
    fig_height: 6
---

```{r setup_chap6x6, include=FALSE}

knitr::opts_chunk$set(results = "asis",
                      warning = FALSE,
                      error = FALSE,
                      message = FALSE,
                      autodep = TRUE)

options(kableExtra.auto_format = F)

# For testing: model_extent <- "Model 1: Lemolo Reservoir to Lemolo Powerhouse #1"


```

##### `r model_extent`

```{r, label=t6x6j, echo=FALSE}

t6x6j_met <- section.model.input %>% 
  dplyr::filter(`Model Extent` %in%  model_extent) %>% 
  dplyr::filter(`Model Location Type` %in%  c("Meteorological")) %>% 
  dplyr::group_by(`Station ID`,`Model Location Type`, `Location Units`, `Data Source`) %>% 
  dplyr::summarize(`Model Location` = toString(unique(sort(`Model Location`))),
                   Parameter = toString(unique(sort(Parameter))))%>% 
  dplyr::ungroup() %>% 
  dplyr::mutate(`Model_Location` = paste0(`Model Location`," ", `Location Units`)) %>% 
  dplyr::select(`Station ID`, `Model_Location`, `Model Location Type`, Parameter, `Data Source`) %>% 
  dplyr::rename(`Model Location Name (Station ID)` = `Station ID`,
                `Model Location` = Model_Location,
                `Input Type` = `Model Location Type`)

t6x6j <- section.model.input %>% 
  dplyr::filter(`Model Extent` %in%  model_extent) %>% 
  dplyr::filter(!`Model Location Type` %in%  c("Calibration Site", "Meteorological")) %>% 
  dplyr::mutate(`Model Location Name (Station ID)` = ifelse(`Station ID` == "No Station ID or unknown" | is.na(`Station ID`),
                                                            `Model Location Name`,
                                                            paste0(`Model Location Name`, " (", `Station ID`, ")"))) %>%  
  dplyr::mutate(`Model_Location` = ifelse(is.na(`Model Location`), NA, paste0(round(`Model Location`,2)," ", `Location Units`))) %>%
  dplyr::mutate(DataSource = ifelse(is.na(`Data Source`),
                                    ifelse(is.na(Note),NA,Note),
                                    ifelse(is.na(Note),`Data Source`,paste0(`Data Source`, ". ", Note))))%>% 
  dplyr::select(`Model Location Name (Station ID)`, `Model_Location`, `Model Location Type`, `Parameter`, DataSource) %>%
  dplyr::rename(`Model Location` = `Model_Location`,
                `Input Type` = `Model Location Type`,
                `Data Source` = DataSource) %>% 
  rbind(t6x6j_met) %>% 
  dplyr::arrange(Parameter,desc(`Model Location`))

if(NROW(t6x6j)>0){
  print(knitr::kable(t6x6j, format = "pandoc", padding = 2,
                     caption = tbls(name = paste0("t6x6j", model_extent),
                                    caption = paste0("Boundary condition and tributary inputs to the existing ", model_extent, "."))))
  
}  else {
  
  cat(paste0("There were no temperature or flow boundary conditions input to this model."))
  
}


```