---
output: 
  word_document:
    reference_docx: N:/Status_and_Trend_Reports/Report_Files/Report_Template.docx
    keep_md: yes
    toc: yes
    fig_caption: yes
    fig_width: 12
    fig_height: 6
---

```{r setup_chap5x34, include=FALSE}

knitr::opts_chunk$set(results = "asis",
                      warning = FALSE,
                      error = FALSE,
                      message = FALSE,
                      autodep = TRUE)

options(kableExtra.auto_format = F)

# For testing: model_extent <- "Model 1: Lemolo Reservoir to Lemolo Powerhouse #1"


```

##### `r model_extent`

```{r, label=`t5x34j`, echo=FALSE}
# for test: model_extent <- "Model 1: Lemolo Reservoir to Lemolo Powerhouse #1"
  
t5x34j <- section.model.input %>% 
  dplyr::filter(`Model Extent` %in%  model_extent) %>% 
  dplyr::filter(`Site Type` == "Calibration Site") %>%
  dplyr::mutate(`Model_Location` = ifelse(is.na(`Model Location`), NA, paste0(`Model Location`," ", `Location Units`))) %>%
  dplyr::arrange(Parameter,desc(`Model Location`)) %>% 
  dplyr::select(`Site Name`, `Station ID`, `Model_Location`, `Parameter`, `Data Source`) %>% 
  dplyr::rename(`Station Description` = `Site Name`,
                `Model Location` = `Model_Location`)

  if(NROW(t5x34j)>0){
    print(knitr::kable(t5x34j, format = "pandoc", padding = 2,
                       caption = tbls(name = paste0("t5x34j", model_extent),
                                      caption = paste0("Calibration sites and parameters used in the existing ", model_extent, "."))))
    
  }

```