tcat45

where_au_yearRound <- paste0("(Pollutant = 'Temperature' AND AU_parameter_category IN ('4A','5') AND period = 'year_round') AND ",
                             "(AU_ID IN ('", paste(tcat45$`Assessment Unit ID`, collapse = "','"),"'))")

where_au_spawning <- paste0("(Pollutant = 'Temperature' AND AU_parameter_category IN ('4A','5') AND period = 'spawn') AND ",
                            "(AU_ID IN ('", paste(tcat45$`Assessment Unit ID`, collapse = "','"),"'))")

where_au_gnis_yearRound <- paste0("(Pollutant = 'Temperature' AND AU_final_status IN ('4A','5') AND period = 'year_round') AND ",
                                  "(AU_ID IN ('", paste(tcat45$`Assessment Unit ID`, collapse = "','"),"'))")

where_au_gnis_spawning <- paste0("(Pollutant = 'Temperature' AND AU_final_status IN ('4A','5') AND period = 'spawn') AND ",
                                  "(AU_ID IN ('", paste(tcat45$`Assessment Unit ID`, collapse = "','"),"'))")

where_au_watershed <- paste0("(AU_ID IN ('", paste(tcat45$`Assessment Unit ID`, collapse = "','"),"'))")

map_basic <- leaflet::leaflet() %>%
  leaflet::fitBounds(lng1 = pro.area.extent[2], lat1 = pro.area.extent[1],
                     lng2 = pro.area.extent[4], lat2 = pro.area.extent[3]) %>%
  # __ IR ----
leaflet.esri::addEsriFeatureLayer(url="https://services.arcgis.com/uUvqNMGPm7axC2dD/ArcGIS/rest/services/IR_2022_Final/FeatureServer/50",
                                  options = leaflet.esri::featureLayerOptions(where = where_au_yearRound),
                                  useServiceSymbology = TRUE,
                                  group = "2022 303(d) Temperature Listed - Streams (Year Round Criteria)",
                                  #pathOptions = leaflet::pathOptions(pane="ir"),
                                  color = "red",
                                  weight = 3,
                                  opacity = 0.8,
                                  fill=FALSE,
                                  highlightOptions = leaflet::highlightOptions(color="red",
                                                                               weight = 5,
                                                                               fillOpacity = 0.5,
                                                                               bringToFront = TRUE,
                                                                               sendToBack = TRUE),
                                  labelProperty = htmlwidgets::JS("function(feature){var props = feature.properties; return props.AU_Name+\" \"}"),
                                  labelOptions = leaflet::labelOptions(#noHide = T,
                                    style = list("color" = "red","font-size" = "12px")),
                                  popupProperty = htmlwidgets::JS(paste0('function(feature){var props = feature.properties; return \"',
                                                                         '<b>AU Name:</b> \"+props.AU_Name+\"',
                                                                         '<br><b>AU ID:</b> \"+props.AU_ID+\"',
                                                                         '<br><b>Impaired Parameter:</b> \"+props.Pollutant+\"',
                                                                         '<br><b>IR Category:</b> \"+props.AU_parameter_category+\"',
                                                                         '<br><b>Year Listed:</b> \"+props.Year_listed+\"',
                                                                         '<br><b>Use Period:</b> \"+props.period+\"',
                                                                         '<br><b>HUC12:</b> \"+props.HUC_12+\"',
                                                                         ' \"}'))) %>%
  leaflet.esri::addEsriFeatureLayer(url="https://services.arcgis.com/uUvqNMGPm7axC2dD/ArcGIS/rest/services/IR_2022_Final/FeatureServer/50",
                                    options = leaflet.esri::featureLayerOptions(where = where_au_spawning),
                                    useServiceSymbology = TRUE,
                                    group = "2022 303(d) Temperature Listed - Streams (Spawning Criteria)",
                                    pathOptions = leaflet::pathOptions(pane="ir"),
                                    color = "red",
                                    weight = 3,
                                    opacity = 0.8,
                                    fill=FALSE,
                                    highlightOptions = leaflet::highlightOptions(color="red",
                                                                                 weight = 5,
                                                                                 fillOpacity = 0.5,
                                                                                 bringToFront = TRUE,
                                                                                 sendToBack = TRUE),
                                    labelProperty = htmlwidgets::JS("function(feature){var props = feature.properties; return props.AU_Name+\" \"}"),
                                    labelOptions = leaflet::labelOptions(#noHide = T,
                                      style = list("color" = "red","font-size" = "12px")),
                                    popupProperty = htmlwidgets::JS(paste0('function(feature){var props = feature.properties; return \"',
                                                                           '<b>AU Name:</b> \"+props.AU_Name+\"',
                                                                           '<br><b>AU ID:</b> \"+props.AU_ID+\"',
                                                                           '<br><b>Impaired Parameter:</b> \"+props.Pollutant+\"',
                                                                           '<br><b>IR Category:</b> \"+props.AU_parameter_category+\"',
                                                                           '<br><b>Year Listed:</b> \"+props.Year_listed+\"',
                                                                           '<br><b>Use Period:</b> \"+props.period+\"',
                                                                           '<br><b>HUC12:</b> \"+props.HUC_12+\"',
                                                                           ' \"}'))) %>%
  leaflet.esri::addEsriFeatureLayer(url="https://services.arcgis.com/uUvqNMGPm7axC2dD/ArcGIS/rest/services/IR_2022_Final/FeatureServer/51",
                                    options = leaflet.esri::featureLayerOptions(where = where_au_yearRound),
                                    useServiceSymbology = TRUE,
                                    group = "2022 303(d) Temperature Listed - Waterbodies (Year Round Criteria)",
                                    #pathOptions = leaflet::pathOptions(pane="ir"),
                                    color = "red",
                                    weight = 2,
                                    opacity = 0.8,
                                    fill=TRUE,
                                    fillColor = "red",
                                    fillOpacity = 0.25,
                                    labelProperty = htmlwidgets::JS("function(feature){var props = feature.properties; return props.AU_Name+\" \"}"),
                                    labelOptions = leaflet::labelOptions(#noHide = T,
                                      style = list("color" = "red","font-size" = "12px")),
                                    highlightOptions = leaflet::highlightOptions(color="red",
                                                                                 weight = 3,
                                                                                 fillOpacity = 0.5,
                                                                                 bringToFront = TRUE,
                                                                                 sendToBack = TRUE),
                                    popupProperty = htmlwidgets::JS(paste0('function(feature){var props = feature.properties; return \"',
                                                                           '<b>AU Name:</b> \"+props.AU_Name+\"',
                                                                           '<br><b>AU ID:</b> \"+props.AU_ID+\"',
                                                                           '<br><b>Impaired Parameter:</b> \"+props.Pollutant+\"',
                                                                           '<br><b>IR Category:</b> \"+props.AU_parameter_category+\"',
                                                                           '<br><b>Year Listed:</b> \"+props.Year_listed+\"',
                                                                           '<br><b>Use Period:</b> \"+props.period+\"',
                                                                           '<br><b>HUC12:</b> \"+props.HUC_12+\"',
                                                                           ' \"}'))) %>%
  leaflet.esri::addEsriFeatureLayer(url="https://services.arcgis.com/uUvqNMGPm7axC2dD/ArcGIS/rest/services/IR_2022_Final/FeatureServer/51",
                                    options = leaflet.esri::featureLayerOptions(where = where_au_spawning),
                                    useServiceSymbology = TRUE,
                                    group = "2022 303(d) Temperature Listed - Waterbodies (Spawning Criteria)",
                                    pathOptions = leaflet::pathOptions(pane="ir"),
                                    color = "red",
                                    weight = 2,
                                    opacity = 0.8,
                                    fill=TRUE,
                                    fillColor = "red",
                                    fillOpacity = 0.25,
                                    labelProperty = htmlwidgets::JS("function(feature){var props = feature.properties; return props.AU_Name+\" \"}"),
                                    labelOptions = leaflet::labelOptions(#noHide = T,
                                      style = list("color" = "red","font-size" = "12px")),
                                    highlightOptions = leaflet::highlightOptions(color="red",
                                                                                 weight = 3,
                                                                                 fillOpacity = 0.5,
                                                                                 bringToFront = TRUE,
                                                                                 sendToBack = TRUE),
                                    popupProperty = htmlwidgets::JS(paste0('function(feature){var props = feature.properties; return \"',
                                                                           '<b>AU Name:</b> \"+props.AU_Name+\"',
                                                                           '<br><b>AU ID:</b> \"+props.AU_ID+\"',
                                                                           '<br><b>Impaired Parameter:</b> \"+props.Pollutant+\"',
                                                                           '<br><b>IR Category:</b> \"+props.AU_parameter_category+\"',
                                                                           '<br><b>Year Listed:</b> \"+props.Year_listed+\"',
                                                                           '<br><b>Use Period:</b> \"+props.period+\"',
                                                                           '<br><b>HUC12:</b> \"+props.HUC_12+\"',
                                                                           ' \"}'))) %>%
  leaflet.esri::addEsriFeatureLayer(url="https://services.arcgis.com/uUvqNMGPm7axC2dD/ArcGIS/rest/services/IR_2022_Final/FeatureServer/52",
                                    options = leaflet.esri::featureLayerOptions(where = where_au_gnis_yearRound),
                                    useServiceSymbology = TRUE,
                                    group = "2022 303(d) Temperature Listed - Watershed (Year Round Criteria)",
                                    #pathOptions = leaflet::pathOptions(pane="ir"),
                                    color = "red",
                                    weight = 1,
                                    opacity = 0.8,
                                    fill = TRUE,
                                    fillColor = "red",
                                    fillOpacity = 0.25,
                                    labelProperty = htmlwidgets::JS("function(feature){var props = feature.properties; return props.AU_GNIS+\" \"}"),
                                    labelOptions = leaflet::labelOptions(#noHide = T,
                                      style = list("color" = "red","font-size" = "12px")),
                                    highlightOptions = leaflet::highlightOptions(color="red",
                                                                                 weight = 3,
                                                                                 fillOpacity = 0.8,
                                                                                 bringToFront = TRUE,
                                                                                 sendToBack = TRUE),
                                    popupProperty = htmlwidgets::JS(paste0('function(feature){var props = feature.properties; return \"',
                                                                           '<b>AU Name:</b> \"+props.AU_Name+\"',
                                                                           '<br><b>AU ID:</b> \"+props.AU_ID+\"',
                                                                           '<br><b>AU GNIS Name:</b> \"+props.AU_GNIS_Name+\"',
                                                                           '<br><b>Impaired Parameter:</b> \"+props.Pollutant+\"',
                                                                           '<br><b>IR AU Category:</b> \"+props.AU_final_status+\"',
                                                                           '<br><b>IR GNIS Category:</b> \"+props.GNIS_final_category+\"',
                                                                           '<br><b>Use Period:</b> \"+props.period+\"',
                                                                           ' \"}'))) %>% 
  leaflet.esri::addEsriFeatureLayer(url="https://services.arcgis.com/uUvqNMGPm7axC2dD/ArcGIS/rest/services/IR_2022_Final/FeatureServer/52",
                                    options = leaflet.esri::featureLayerOptions(where = where_au_gnis_spawning),
                                    useServiceSymbology = TRUE,
                                    group = "2022 303(d) Temperature Listed - Watershed (Spawning Criteria))",
                                    #pathOptions = leaflet::pathOptions(pane="ir"),
                                    color = "red",
                                    weight = 1,
                                    opacity = 0.8,
                                    fill = TRUE,
                                    fillColor = "red",
                                    fillOpacity = 0.25,
                                    labelProperty = htmlwidgets::JS("function(feature){var props = feature.properties; return props.AU_GNIS+\" \"}"),
                                    labelOptions = leaflet::labelOptions(#noHide = T,
                                      style = list("color" = "red","font-size" = "12px")),
                                    highlightOptions = leaflet::highlightOptions(color="red",
                                                                                 weight = 3,
                                                                                 fillOpacity = 0.8,
                                                                                 bringToFront = TRUE,
                                                                                 sendToBack = TRUE),
                                    popupProperty = htmlwidgets::JS(paste0('function(feature){var props = feature.properties; return \"',
                                                                           '<b>AU Name:</b> \"+props.AU_Name+\"',
                                                                           '<br><b>AU ID:</b> \"+props.AU_ID+\"',
                                                                           '<br><b>AU GNIS Name:</b> \"+props.AU_GNIS_Name+\"',
                                                                           '<br><b>Impaired Parameter:</b> \"+props.Pollutant+\"',
                                                                           '<br><b>IR AU Category:</b> \"+props.AU_final_status+\"',
                                                                           '<br><b>IR GNIS Category:</b> \"+props.GNIS_final_category+\"',
                                                                           '<br><b>Use Period:</b> \"+props.period+\"',
                                                                           ' \"}'))) %>% 
  leaflet.esri::addEsriFeatureLayer(url="https://services.arcgis.com/uUvqNMGPm7axC2dD/ArcGIS/rest/services/IR_2022_Final/FeatureServer/44",
                                    options = leaflet.esri::featureLayerOptions(where = where_au_watershed),
                                    useServiceSymbology = TRUE,
                                    group = "2022 303(d) Temperature Listed - Watershed (Year Round Criteria))",
                                    #pathOptions = leaflet::pathOptions(pane="ir"),
                                    color = "red",
                                    weight = 1,
                                    opacity = 0.8,
                                    fill = TRUE,
                                    fillColor = "red",
                                    fillOpacity = 0.25,
                                    labelProperty = htmlwidgets::JS("function(feature){var props = feature.properties; return props.AU_Name+\" \"}"),
                                    labelOptions = leaflet::labelOptions(#noHide = T,
                                      style = list("color" = "red","font-size" = "12px")),
                                    highlightOptions = leaflet::highlightOptions(color="red",
                                                                                 weight = 3,
                                                                                 fillOpacity = 0.8,
                                                                                 bringToFront = TRUE,
                                                                                 sendToBack = TRUE),
                                    popupProperty = htmlwidgets::JS(paste0('function(feature){var props = feature.properties; return \"',
                                                                           '<b>AU Name:</b> \"+props.AU_Name+\"',
                                                                           '<br><b>AU ID:</b> \"+props.AU_ID+\"',
                                                                           ' \"}'))) %>% 
  leaflet.esri::addEsriFeatureLayer(url="https://services.arcgis.com/uUvqNMGPm7axC2dD/ArcGIS/rest/services/IR_2022_Final/FeatureServer/44",
                                    options = leaflet.esri::featureLayerOptions(where = where_au_watershed),
                                    useServiceSymbology = TRUE,
                                    group = "2022 303(d) Temperature Listed - Watershed (Spawning Criteria))",
                                    #pathOptions = leaflet::pathOptions(pane="ir"),
                                    color = "red",
                                    weight = 1,
                                    opacity = 0.8,
                                    fill = TRUE,
                                    fillColor = "red",
                                    fillOpacity = 0.25,
                                    labelProperty = htmlwidgets::JS("function(feature){var props = feature.properties; return props.AU_Name+\" \"}"),
                                    labelOptions = leaflet::labelOptions(#noHide = T,
                                      style = list("color" = "red","font-size" = "12px")),
                                    highlightOptions = leaflet::highlightOptions(color="red",
                                                                                 weight = 3,
                                                                                 fillOpacity = 0.8,
                                                                                 bringToFront = TRUE,
                                                                                 sendToBack = TRUE),
                                    popupProperty = htmlwidgets::JS(paste0('function(feature){var props = feature.properties; return \"',
                                                                           '<b>AU Name:</b> \"+props.AU_Name+\"',
                                                                           '<br><b>AU ID:</b> \"+props.AU_ID+\"',
                                                                           ' \"}'))) %>% 
  
  map_basic

########################
# __ HUCs ----
leaflet.esri::addEsriFeatureLayer(url="https://arcgis.deq.state.or.us/arcgis/rest/services/WQ/WBD/MapServer/1",
                                  options = leaflet.esri::featureLayerOptions(where = where_huc8),
                                  group = "HUC8",
                                  pathOptions = leaflet::pathOptions(pane="huc8"),
                                  weight = 4,
                                  color = "black",
                                  opacity = 3,
                                  fillColor = "transparent",
                                  fillOpacity = 0,
                                  highlightOptions = leaflet::highlightOptions(color="black",
                                                                               weight = 5,
                                                                               fill=TRUE,
                                                                               fillColor = "black",
                                                                               fillOpacity = 0.5,
                                                                               bringToFront = TRUE,
                                                                               sendToBack = TRUE),
                                  labelProperty = htmlwidgets::JS("function(feature){var props = feature.properties; return props.Name+\" \"}"),
                                  labelOptions = leaflet::labelOptions(style = list("color" = "black","font-size" = "20px")),
                                  popupProperty = htmlwidgets::JS(paste0('function(feature){var props = feature.properties; return \"',
                                                                         '<b>Name:</b> \"+props.Name+\"',
                                                                         '<br><b>HUC8:</b> \"+props.HUC8+\"',
                                                                         ' \"}'))) %>% 
  
#######################
# REST au and gnis

where_au_gnis_yearRound <- paste0("(Pollutant = 'Temperature' AND AU_final_status IN ('5') AND period = 'year_round') AND ",
                                  "(AU_ID IN ('", paste(tcat45$`Assessment Unit ID`, collapse = "','"),"'))")

where_au_gnis_spawning <- paste0("(Pollutant = 'Temperature' AND AU_final_status IN ('5') AND period = 'spawn') AND ",
                                 "(AU_ID IN ('", paste(tcat45$`Assessment Unit ID`, collapse = "','"),"'))")

where_au <- paste0("(AU_ID IN ('", paste(tcat45$`Assessment Unit ID`, collapse = "','"),"'))")

leaflet.esri::addEsriFeatureLayer(url="https://services.arcgis.com/uUvqNMGPm7axC2dD/ArcGIS/rest/services/IR_2022_Final/FeatureServer/52",
                                  options = leaflet.esri::featureLayerOptions(where = where_au_gnis_yearRound),
                                  useServiceSymbology = TRUE,
                                  group = "2022 303(d) Temperature Listed - Watershed (Year Round Criteria)",
                                  pathOptions = leaflet::pathOptions(pane="ir"),
                                  color = "red",
                                  weight = 1,
                                  opacity = 0.8,
                                  fill = TRUE,
                                  fillColor = "red",
                                  fillOpacity = 0.25,
                                  labelProperty = htmlwidgets::JS("function(feature){var props = feature.properties; return props.AU_GNIS+\" \"}"),
                                  labelOptions = leaflet::labelOptions(#noHide = T,
                                    style = list("color" = "red","font-size" = "12px")),
                                  highlightOptions = leaflet::highlightOptions(color="red",
                                                                               weight = 3,
                                                                               fillOpacity = 0.8,
                                                                               bringToFront = TRUE,
                                                                               sendToBack = TRUE),
                                  popupProperty = htmlwidgets::JS(paste0('function(feature){var props = feature.properties; return \"',
                                                                         '<b>AU Name:</b> \"+props.AU_Name+\"',
                                                                         '<br><b>AU ID:</b> \"+props.AU_ID+\"',
                                                                         '<br><b>AU GNIS Name:</b> \"+props.AU_GNIS_Name+\"',
                                                                         '<br><b>Impaired Parameter:</b> \"+props.Pollutant+\"',
                                                                         '<br><b>IR AU Category:</b> \"+props.AU_final_status+\"',
                                                                         '<br><b>IR GNIS Category:</b> \"+props.GNIS_final_category+\"',
                                                                         '<br><b>Use Period:</b> \"+props.period+\"',
                                                                         ' \"}'))) %>% 
  leaflet.esri::addEsriFeatureLayer(url="https://services.arcgis.com/uUvqNMGPm7axC2dD/ArcGIS/rest/services/IR_2022_Final/FeatureServer/52",
                                    options = leaflet.esri::featureLayerOptions(where = where_au_gnis_spawning),
                                    useServiceSymbology = TRUE,
                                    group = "2022 303(d) Temperature Listed - Watershed (Spawning Criteria))",
                                    pathOptions = leaflet::pathOptions(pane="ir"),
                                    color = "red",
                                    weight = 1,
                                    opacity = 0.8,
                                    fill = TRUE,
                                    fillColor = "red",
                                    fillOpacity = 0.25,
                                    labelProperty = htmlwidgets::JS("function(feature){var props = feature.properties; return props.AU_GNIS+\" \"}"),
                                    labelOptions = leaflet::labelOptions(#noHide = T,
                                      style = list("color" = "red","font-size" = "12px")),
                                    highlightOptions = leaflet::highlightOptions(color="red",
                                                                                 weight = 3,
                                                                                 fillOpacity = 0.8,
                                                                                 bringToFront = TRUE,
                                                                                 sendToBack = TRUE),
                                    popupProperty = htmlwidgets::JS(paste0('function(feature){var props = feature.properties; return \"',
                                                                           '<b>AU Name:</b> \"+props.AU_Name+\"',
                                                                           '<br><b>AU ID:</b> \"+props.AU_ID+\"',
                                                                           '<br><b>AU GNIS Name:</b> \"+props.AU_GNIS_Name+\"',
                                                                           '<br><b>Impaired Parameter:</b> \"+props.Pollutant+\"',
                                                                           '<br><b>IR AU Category:</b> \"+props.AU_final_status+\"',
                                                                           '<br><b>IR GNIS Category:</b> \"+props.GNIS_final_category+\"',
                                                                           '<br><b>Use Period:</b> \"+props.period+\"',
                                                                           ' \"}'))) %>% 
  leaflet.esri::addEsriFeatureLayer(url="https://services.arcgis.com/uUvqNMGPm7axC2dD/ArcGIS/rest/services/IR_2022_Final/FeatureServer/44",
                                    options = leaflet.esri::featureLayerOptions(where = where_au),
                                    useServiceSymbology = TRUE,
                                    group = "2022 303(d) Temperature Listed - Watershed (Year Round Criteria))",
                                    pathOptions = leaflet::pathOptions(pane="ir"),
                                    color = "red",
                                    weight = 1,
                                    opacity = 0.8,
                                    fill = TRUE,
                                    fillColor = "red",
                                    fillOpacity = 0.25,
                                    labelProperty = htmlwidgets::JS("function(feature){var props = feature.properties; return props.AU_Name+\" \"}"),
                                    labelOptions = leaflet::labelOptions(#noHide = T,
                                      style = list("color" = "red","font-size" = "12px")),
                                    highlightOptions = leaflet::highlightOptions(color="red",
                                                                                 weight = 3,
                                                                                 fillOpacity = 0.8,
                                                                                 bringToFront = TRUE,
                                                                                 sendToBack = TRUE),
                                    popupProperty = htmlwidgets::JS(paste0('function(feature){var props = feature.properties; return \"',
                                                                           '<b>AU Name:</b> \"+props.AU_Name+\"',
                                                                           '<br><b>AU ID:</b> \"+props.AU_ID+\"',
                                                                           ' \"}'))) %>% 
  leaflet.esri::addEsriFeatureLayer(url="https://services.arcgis.com/uUvqNMGPm7axC2dD/ArcGIS/rest/services/IR_2022_Final/FeatureServer/44",
                                    options = leaflet.esri::featureLayerOptions(where = where_au),
                                    useServiceSymbology = TRUE,
                                    group = "2022 303(d) Temperature Listed - Watershed (Spawning Criteria))",
                                    pathOptions = leaflet::pathOptions(pane="ir"),
                                    color = "red",
                                    weight = 1,
                                    opacity = 0.8,
                                    fill = TRUE,
                                    fillColor = "red",
                                    fillOpacity = 0.25,
                                    labelProperty = htmlwidgets::JS("function(feature){var props = feature.properties; return props.AU_Name+\" \"}"),
                                    labelOptions = leaflet::labelOptions(#noHide = T,
                                      style = list("color" = "red","font-size" = "12px")),
                                    highlightOptions = leaflet::highlightOptions(color="red",
                                                                                 weight = 3,
                                                                                 fillOpacity = 0.8,
                                                                                 bringToFront = TRUE,
                                                                                 sendToBack = TRUE),
                                    popupProperty = htmlwidgets::JS(paste0('function(feature){var props = feature.properties; return \"',
                                                                           '<b>AU Name:</b> \"+props.AU_Name+\"',
                                                                           '<br><b>AU ID:</b> \"+props.AU_ID+\"',
                                                                           ' \"}'))) %>% 
  
  ##########
  leaflet.esri::addEsriFeatureLayer(url="https://services.arcgis.com/uUvqNMGPm7axC2dD/ArcGIS/rest/services/IR_2022_Final/FeatureServer/50",
                                    options = leaflet.esri::featureLayerOptions(where = where_au_yearRound),
                                    useServiceSymbology = TRUE,
                                    group = "2022 303(d) Temperature Listed - Streams (Year Round Criteria)",
                                    pathOptions = leaflet::pathOptions(pane="ir"),
                                    color = "red",
                                    weight = 3,
                                    opacity = 0.8,
                                    fill=FALSE,
                                    highlightOptions = leaflet::highlightOptions(color="red",
                                                                                 weight = 5,
                                                                                 fillOpacity = 0.5,
                                                                                 bringToFront = TRUE,
                                                                                 sendToBack = TRUE),
                                    labelProperty = htmlwidgets::JS("function(feature){var props = feature.properties; return props.AU_Name+\" \"}"),
                                    labelOptions = leaflet::labelOptions(#noHide = T,
                                      style = list("color" = "red","font-size" = "12px")),
                                    popupProperty = htmlwidgets::JS(paste0('function(feature){var props = feature.properties; return \"',
                                                                           '<b>AU Name:</b> \"+props.AU_Name+\"',
                                                                           '<br><b>AU ID:</b> \"+props.AU_ID+\"',
                                                                           '<br><b>Impaired Parameter:</b> \"+props.Pollutant+\"',
                                                                           '<br><b>IR Category:</b> \"+props.AU_parameter_category+\"',
                                                                           '<br><b>Year Listed:</b> \"+props.Year_listed+\"',
                                                                           '<br><b>Use Period:</b> \"+props.period+\"',
                                                                           '<br><b>HUC12:</b> \"+props.HUC_12+\"',
                                                                           ' \"}'))) %>%
  leaflet.esri::addEsriFeatureLayer(url="https://services.arcgis.com/uUvqNMGPm7axC2dD/ArcGIS/rest/services/IR_2022_Final/FeatureServer/50",
                                    options = leaflet.esri::featureLayerOptions(where = where_au_spawning),
                                    useServiceSymbology = TRUE,
                                    group = "2022 303(d) Temperature Listed - Streams (Spawning Criteria)",
                                    pathOptions = leaflet::pathOptions(pane="ir"),
                                    color = "red",
                                    weight = 3,
                                    opacity = 0.8,
                                    fill=FALSE,
                                    highlightOptions = leaflet::highlightOptions(color="red",
                                                                                 weight = 5,
                                                                                 fillOpacity = 0.5,
                                                                                 bringToFront = TRUE,
                                                                                 sendToBack = TRUE),
                                    labelProperty = htmlwidgets::JS("function(feature){var props = feature.properties; return props.AU_Name+\" \"}"),
                                    labelOptions = leaflet::labelOptions(#noHide = T,
                                      style = list("color" = "red","font-size" = "12px")),
                                    popupProperty = htmlwidgets::JS(paste0('function(feature){var props = feature.properties; return \"',
                                                                           '<b>AU Name:</b> \"+props.AU_Name+\"',
                                                                           '<br><b>AU ID:</b> \"+props.AU_ID+\"',
                                                                           '<br><b>Impaired Parameter:</b> \"+props.Pollutant+\"',
                                                                           '<br><b>IR Category:</b> \"+props.AU_parameter_category+\"',
                                                                           '<br><b>Year Listed:</b> \"+props.Year_listed+\"',
                                                                           '<br><b>Use Period:</b> \"+props.period+\"',
                                                                           '<br><b>HUC12:</b> \"+props.HUC_12+\"',
                                                                           ' \"}'))) %>%
  
  
  ######### WMS
  # ____ TMDL project scope ----
leaflet.esri::addEsriFeatureLayer(url="https://services.arcgis.com/uUvqNMGPm7axC2dD/ArcGIS/rest/services/IR_2022_Final/FeatureServer/34",
                                  options = leaflet.esri::featureLayerOptions(where = where_au),
                                  useServiceSymbology = TRUE,
                                  group = "TMDL Project Scope",
                                  pathOptions = leaflet::pathOptions(pane="area"),
                                  weight = 10,
                                  color = "black",
                                  opacity = 1,
                                  fill=FALSE) %>%
  leaflet.esri::addEsriFeatureLayer(url="https://services.arcgis.com/uUvqNMGPm7axC2dD/ArcGIS/rest/services/IR_2022_Final/FeatureServer/43",
                                    options = leaflet.esri::featureLayerOptions(where = where_au),
                                    useServiceSymbology = TRUE,
                                    group = "TMDL Project Scope",
                                    pathOptions = leaflet::pathOptions(pane="area"),
                                    weight = 10,
                                    color = "black",
                                    opacity = 1,
                                    fill=FALSE) %>%
  
  
  # __ HUCs ----
leaflet.esri::addEsriFeatureLayer(url="https://arcgis.deq.state.or.us/arcgis/rest/services/WQ/WBD/MapServer/1",
                                  options = leaflet.esri::featureLayerOptions(where = where_huc8),
                                  group = "HUC8",
                                  pathOptions = leaflet::pathOptions(pane="huc8"),
                                  weight = 4,
                                  color = "black",
                                  opacity = 1,
                                  fillColor = "transparent",
                                  fillOpacity = 0,
                                  highlightOptions = leaflet::highlightOptions(color="black",
                                                                               weight = 5,
                                                                               fill=TRUE,
                                                                               fillColor = "black",
                                                                               fillOpacity = 0.5,
                                                                               bringToFront = TRUE,
                                                                               sendToBack = TRUE),
                                  labelProperty = htmlwidgets::JS("function(feature){var props = feature.properties; return props.Name+\" \"}"),
                                  labelOptions = leaflet::labelOptions(style = list("color" = "black","font-size" = "20px")),
                                  popupProperty = htmlwidgets::JS(paste0('function(feature){var props = feature.properties; return \"',
                                                                         '<b>Name:</b> \"+props.Name+\"',
                                                                         '<br><b>HUC8:</b> \"+props.HUC8+\"',
                                                                         ' \"}'))) 
  
  
plot(pro_area)
plot(pro_scope_rivers[1])
plot(pro_scope_waterbodies[1])
plot(pro_scope_watershed[1])

###########33
leaflet.esri::addEsriFeatureLayer(url="https://services.arcgis.com/uUvqNMGPm7axC2dD/ArcGIS/rest/services/IR_2022_Final/FeatureServer/50",
                                  options = leaflet.esri::featureLayerOptions(where = where_au_yearRound),
                                  useServiceSymbology = TRUE,
                                  group = "2022 303(d) Temperature Listed - Streams (Year Round Criteria)",
                                  pathOptions = leaflet::pathOptions(pane="ir"),
                                  color = "red",
                                  weight = 3,
                                  opacity = 0.8,
                                  fill=FALSE,
                                  highlightOptions = leaflet::highlightOptions(color="red",
                                                                               weight = 5,
                                                                               fillOpacity = 0.5,
                                                                               bringToFront = TRUE,
                                                                               sendToBack = TRUE),
                                  labelProperty = htmlwidgets::JS("function(feature){var props = feature.properties; return props.AU_Name+\" \"}"),
                                  labelOptions = leaflet::labelOptions(#noHide = T,
                                    style = list("color" = "red","font-size" = "12px")),
                                  popupProperty = htmlwidgets::JS(paste0('function(feature){var props = feature.properties; return \"',
                                                                         '<b>AU Name:</b> \"+props.AU_Name+\"',
                                                                         '<br><b>AU ID:</b> \"+props.AU_ID+\"',
                                                                         '<br><b>Impaired Parameter:</b> \"+props.Pollutant+\"',
                                                                         '<br><b>IR Category:</b> \"+props.AU_parameter_category+\"',
                                                                         '<br><b>Year Listed:</b> \"+props.Year_listed+\"',
                                                                         '<br><b>Use Period:</b> \"+props.period+\"',
                                                                         '<br><b>HUC12:</b> \"+props.HUC_12+\"',
                                                                         ' \"}'))) %>%
  leaflet.esri::addEsriFeatureLayer(url="https://services.arcgis.com/uUvqNMGPm7axC2dD/ArcGIS/rest/services/IR_2022_Final/FeatureServer/50",
                                    options = leaflet.esri::featureLayerOptions(where = where_au_spawning),
                                    useServiceSymbology = TRUE,
                                    group = "2022 303(d) Temperature Listed - Streams (Spawning Criteria)",
                                    pathOptions = leaflet::pathOptions(pane="ir"),
                                    color = "red",
                                    weight = 3,
                                    opacity = 0.8,
                                    fill=FALSE,
                                    highlightOptions = leaflet::highlightOptions(color="red",
                                                                                 weight = 5,
                                                                                 fillOpacity = 0.5,
                                                                                 bringToFront = TRUE,
                                                                                 sendToBack = TRUE),
                                    labelProperty = htmlwidgets::JS("function(feature){var props = feature.properties; return props.AU_Name+\" \"}"),
                                    labelOptions = leaflet::labelOptions(#noHide = T,
                                      style = list("color" = "red","font-size" = "12px")),
                                    popupProperty = htmlwidgets::JS(paste0('function(feature){var props = feature.properties; return \"',
                                                                           '<b>AU Name:</b> \"+props.AU_Name+\"',
                                                                           '<br><b>AU ID:</b> \"+props.AU_ID+\"',
                                                                           '<br><b>Impaired Parameter:</b> \"+props.Pollutant+\"',
                                                                           '<br><b>IR Category:</b> \"+props.AU_parameter_category+\"',
                                                                           '<br><b>Year Listed:</b> \"+props.Year_listed+\"',
                                                                           '<br><b>Use Period:</b> \"+props.period+\"',
                                                                           '<br><b>HUC12:</b> \"+props.HUC_12+\"',
                                                                           ' \"}'))) %>%
  leaflet.esri::addEsriFeatureLayer(url="https://services.arcgis.com/uUvqNMGPm7axC2dD/ArcGIS/rest/services/IR_2022_Final/FeatureServer/51",
                                    options = leaflet.esri::featureLayerOptions(where = where_au_yearRound),
                                    useServiceSymbology = TRUE,
                                    group = "2022 303(d) Temperature Listed - Waterbodies (Year Round Criteria)",
                                    pathOptions = leaflet::pathOptions(pane="ir"),
                                    color = "red",
                                    weight = 2,
                                    opacity = 0.8,
                                    fill=TRUE,
                                    fillColor = "red",
                                    fillOpacity = 0.25,
                                    labelProperty = htmlwidgets::JS("function(feature){var props = feature.properties; return props.AU_Name+\" \"}"),
                                    labelOptions = leaflet::labelOptions(#noHide = T,
                                      style = list("color" = "red","font-size" = "12px")),
                                    highlightOptions = leaflet::highlightOptions(color="red",
                                                                                 weight = 3,
                                                                                 fillOpacity = 0.5,
                                                                                 bringToFront = TRUE,
                                                                                 sendToBack = TRUE),
                                    popupProperty = htmlwidgets::JS(paste0('function(feature){var props = feature.properties; return \"',
                                                                           '<b>AU Name:</b> \"+props.AU_Name+\"',
                                                                           '<br><b>AU ID:</b> \"+props.AU_ID+\"',
                                                                           '<br><b>Impaired Parameter:</b> \"+props.Pollutant+\"',
                                                                           '<br><b>IR Category:</b> \"+props.AU_parameter_category+\"',
                                                                           '<br><b>Year Listed:</b> \"+props.Year_listed+\"',
                                                                           '<br><b>Use Period:</b> \"+props.period+\"',
                                                                           '<br><b>HUC12:</b> \"+props.HUC_12+\"',
                                                                           ' \"}'))) %>%
  leaflet.esri::addEsriFeatureLayer(url="https://services.arcgis.com/uUvqNMGPm7axC2dD/ArcGIS/rest/services/IR_2022_Final/FeatureServer/51",
                                    options = leaflet.esri::featureLayerOptions(where = where_au_spawning),
                                    useServiceSymbology = TRUE,
                                    group = "2022 303(d) Temperature Listed - Waterbodies (Spawning Criteria)",
                                    pathOptions = leaflet::pathOptions(pane="ir"),
                                    color = "red",
                                    weight = 2,
                                    opacity = 0.8,
                                    fill=TRUE,
                                    fillColor = "red",
                                    fillOpacity = 0.25,
                                    labelProperty = htmlwidgets::JS("function(feature){var props = feature.properties; return props.AU_Name+\" \"}"),
                                    labelOptions = leaflet::labelOptions(#noHide = T,
                                      style = list("color" = "red","font-size" = "12px")),
                                    highlightOptions = leaflet::highlightOptions(color="red",
                                                                                 weight = 3,
                                                                                 fillOpacity = 0.5,
                                                                                 bringToFront = TRUE,
                                                                                 sendToBack = TRUE),
                                    popupProperty = htmlwidgets::JS(paste0('function(feature){var props = feature.properties; return \"',
                                                                           '<b>AU Name:</b> \"+props.AU_Name+\"',
                                                                           '<br><b>AU ID:</b> \"+props.AU_ID+\"',
                                                                           '<br><b>Impaired Parameter:</b> \"+props.Pollutant+\"',
                                                                           '<br><b>IR Category:</b> \"+props.AU_parameter_category+\"',
                                                                           '<br><b>Year Listed:</b> \"+props.Year_listed+\"',
                                                                           '<br><b>Use Period:</b> \"+props.period+\"',
                                                                           '<br><b>HUC12:</b> \"+props.HUC_12+\"',
                                                                           ' \"}'))) %>%
  leaflet.esri::addEsriFeatureLayer(url="https://services.arcgis.com/uUvqNMGPm7axC2dD/ArcGIS/rest/services/IR_2022_Final/FeatureServer/63",
                                    options = leaflet.esri::featureLayerOptions(where = where_au_yearRound),
                                    useServiceSymbology = TRUE,
                                    group = "2022 303(d) Temperature Listed - Watershed (Year Round Criteria)",
                                    pathOptions = leaflet::pathOptions(pane="ir"),
                                    color = "red",
                                    weight = 2,
                                    opacity = 0.8,
                                    fill=TRUE,
                                    fillColor = "red",
                                    fillOpacity = 0.25,
                                    labelProperty = htmlwidgets::JS("function(feature){var props = feature.properties; return props.AU_Name+\" \"}"),
                                    labelOptions = leaflet::labelOptions(#noHide = T,
                                      style = list("color" = "red","font-size" = "12px")),
                                    highlightOptions = leaflet::highlightOptions(color="red",
                                                                                 weight = 3,
                                                                                 fillOpacity = 0.5,
                                                                                 bringToFront = TRUE,
                                                                                 sendToBack = TRUE),
                                    popupProperty = htmlwidgets::JS(paste0('function(feature){var props = feature.properties; return \"',
                                                                           '<b>AU Name:</b> \"+props.AU_Name+\"',
                                                                           '<br><b>AU ID:</b> \"+props.AU_ID+\"',
                                                                           '<br><b>Impaired Parameter:</b> \"+props.Pollutant+\"',
                                                                           '<br><b>IR Category:</b> \"+props.AU_parameter_category+\"',
                                                                           '<br><b>Year Listed:</b> \"+props.Year_listed+\"',
                                                                           '<br><b>Use Period:</b> \"+props.period+\"',
                                                                           '<br><b>HUC12:</b> \"+props.HUC_12+\"',
                                                                           ' \"}'))) %>%
  leaflet.esri::addEsriFeatureLayer(url="https://services.arcgis.com/uUvqNMGPm7axC2dD/ArcGIS/rest/services/IR_2022_Final/FeatureServer/63",
                                    options = leaflet.esri::featureLayerOptions(where = where_au_spawning),
                                    useServiceSymbology = TRUE,
                                    group = "2022 303(d) Temperature Listed - Watershed (Spawning Criteria)",
                                    pathOptions = leaflet::pathOptions(pane="ir"),
                                    color = "red",
                                    weight = 2,
                                    opacity = 0.8,
                                    fill=TRUE,
                                    fillColor = "red",
                                    fillOpacity = 0.25,
                                    labelProperty = htmlwidgets::JS("function(feature){var props = feature.properties; return props.AU_Name+\" \"}"),
                                    labelOptions = leaflet::labelOptions(#noHide = T,
                                      style = list("color" = "red","font-size" = "12px")),
                                    highlightOptions = leaflet::highlightOptions(color="red",
                                                                                 weight = 3,
                                                                                 fillOpacity = 0.5,
                                                                                 bringToFront = TRUE,
                                                                                 sendToBack = TRUE),
                                    popupProperty = htmlwidgets::JS(paste0('function(feature){var props = feature.properties; return \"',
                                                                           '<b>AU Name:</b> \"+props.AU_Name+\"',
                                                                           '<br><b>AU ID:</b> \"+props.AU_ID+\"',
                                                                           '<br><b>Impaired Parameter:</b> \"+props.Pollutant+\"',
                                                                           '<br><b>IR Category:</b> \"+props.AU_parameter_category+\"',
                                                                           '<br><b>Year Listed:</b> \"+props.Year_listed+\"',
                                                                           '<br><b>Use Period:</b> \"+props.period+\"',
                                                                           '<br><b>HUC12:</b> \"+props.HUC_12+\"',
                                                                           ' \"}'))) %>%
  
  
  where_au_rivers <- paste0("(AU_ID IN ('", paste(wms.au.id, collapse = "','"),"'))")
where_au_waterbodies <- paste0("(AU_ID IN ('", paste(wms.au.id, collapse = "','"),"'))")
where_au_watershed <- paste0("(AU_ID IN ('", paste(wms.au.id, collapse = "','"),"'))")


group.names <- c("TMDL Project Scope",
                 dta.stations.mod %>% dplyr::pull(group_name),
                 "HUC8","HUC10","HUC12",
                 ir.grps,
                 "Fish Use Designations",
                 "Salmon and Steelhead Spawning Use Designations",
                 "Stream Names (USGS NHD)",
                 "Oregon Imagery")

group.names.hide <- c("TMDL Project Scope",
                      dta.stations.mod[-1,] %>% dplyr::pull(group_name),
                      "HUC8","HUC10","HUC12",
                      ir.grps,
                      "Fish Use Designations",
                      "Salmon and Steelhead Spawning Use Designations",
                      "Stream Names (USGS NHD)",
                      "Oregon Imagery")

where_huc12_50_1 <- paste0("HUC12 IN ('", paste(subbasin_huc12[1:150], collapse = "','"),"')")
where_huc12_50_2 <- paste0("HUC12 IN ('", paste(subbasin_huc12[151:300], collapse = "','"),"')")
where_huc12_50_3 <- paste0("HUC12 IN ('", paste(subbasin_huc12[301:450], collapse = "','"),"')")

map_basic <- leaflet::leaflet() %>%
  leaflet.esri::addEsriFeatureLayer(url="https://arcgis.deq.state.or.us/arcgis/rest/services/WQ/OR_DMAs/MapServer/0",
                                    options = leaflet.esri::featureLayerOptions(where = where_huc8_lower)) %>% 
  leaflet.esri::addEsriFeatureLayer(url="https://arcgis.deq.state.or.us/arcgis/rest/services/WQ/OR_DMAs/MapServer/0",
                                    options = leaflet.esri::featureLayerOptions(where = where_huc8_middle)) %>% 
  leaflet.esri::addEsriFeatureLayer(url="https://arcgis.deq.state.or.us/arcgis/rest/services/WQ/OR_DMAs/MapServer/0",
                                    options = leaflet.esri::featureLayerOptions(where = where_huc8_southern))

map_basic


save.image(file = "WillametteSubbasinMapData.RData")


# __ WQS ----
leaflet.esri::addEsriFeatureLayer(url="https://arcgis.deq.state.or.us/arcgis/rest/services/WQ/WQStandards_WM/MapServer/0",
                                  options = leaflet.esri::featureLayerOptions(where = reachcode,
                                                                              style = tempWQScolor),
                                  pathOptions = leaflet::pathOptions(pane="wqs1"),
                                  useServiceSymbology = FALSE,
                                  group = "Fish Use Designations",
                                  weight = 3,
                                  opacity = 1,
                                  fill=FALSE,
                                  popupOptions = leaflet::popupOptions(maxWidth = 600, maxHeight = 500),
                                  popupProperty = htmlwidgets::JS(paste0('function(feature){var props = feature.properties; return \"',
                                                                         '<b>Waterbody Name:</b> \"+props.GNIS_Name+\"',
                                                                         '<br><b>Temperature Criteria:</b> \"+props.Temperature_Criteria+\"',
                                                                         '<br><b>Non Spawning 7DADM deg-C:</b> \"+props.Temperature_Criterion_7dADM_C+\"',
                                                                         '<br><b>Temperature Spawning Dates:</b> \"+props.Temperature_Spawn_dates+\"',
                                                                         ' \"}')))



map_basic <- leaflet::leaflet() %>%
  leaflet.esri::addEsriFeatureLayer(url="https://services.arcgis.com/uUvqNMGPm7axC2dD/ArcGIS/rest/services/OR_DMAs/FeatureServer/0",
                                    options = leaflet.esri::featureLayerOptions(where = where_huc8_lower,
                                                                                style = DMAcolor),
                                    # group = "Land Ownership or Jurisdiction",
                                    # pathOptions = leaflet::pathOptions(pane="dma1"),
                                    weight = 0.5,
                                    fill = TRUE,
                                    fillOpacity = 0.75,
                                    opacity = 0,
                                    highlightOptions = leaflet::highlightOptions(color="black",
                                                                                 weight = 3,
                                                                                 fill=TRUE,
                                                                                 fillColor = "black",
                                                                                 fillOpacity = 0.5,
                                                                                 bringToFront = TRUE,
                                                                                 sendToBack = TRUE),
                                    labelProperty = htmlwidgets::JS("function(feature){var props = feature.properties; return props.DMA_RP+\" \"}"),
                                    labelOptions = leaflet::labelOptions(style = list("color" = "black","font-size" = "20px")),
                                    popupProperty = htmlwidgets::JS(paste0('function(feature){var props = feature.properties; return \"',
                                                                           '<b>Land Ownership or Jurisdiction:</b> \"+props.DMA_RP+\"',
                                                                           '<br>\"+props.DMA_RP_Cl+\"',
                                                                           '<br><b>HUC12:</b> \"+props.HUC12+\"',
                                                                           '<br><b>Version:</b> \"+props.Version+\"',
                                                                           ' \"}')))

where_huc8_lower
"Land Ownership or Jurisdiction (Lower Willamette and Clackamas Subbasins"

where_huc8_middle
"Middle Willamette Subbasins" 
where_huc8_southern
"Southern Willamette Subbasins" 

"Land Ownership or Jurisdiction (Lower Willamette and Clackamas Subbasins)",
"Land Ownership or Jurisdiction (Middle Willamette Subbasins)",
"Land Ownership or Jurisdiction (Southern Willamette Subbasins)",
                                    
map_basic <- leaflet::leaflet() %>%
  leaflet.esri::addEsriFeatureLayer(url="https://services.arcgis.com/uUvqNMGPm7axC2dD/ArcGIS/rest/services/OR_DMAs/FeatureServer/0",
                                    options = leaflet.esri::featureLayerOptions(where = where_huc12_1,
                                                                                style = DMAcolor),
                                    group = "Land Ownership or Jurisdiction",
                                    pathOptions = leaflet::pathOptions(pane="dma1"),
                                    weight = 0.5,
                                    fill = TRUE,
                                    fillOpacity = 0.75,
                                    opacity = 0,
                                    highlightOptions = leaflet::highlightOptions(color="black",
                                                                                 weight = 3,
                                                                                 fill=TRUE,
                                                                                 fillColor = "black",
                                                                                 fillOpacity = 0.5,
                                                                                 bringToFront = TRUE,
                                                                                 sendToBack = TRUE),
                                    labelProperty = htmlwidgets::JS("function(feature){var props = feature.properties; return props.DMA_RP+\" \"}"),
                                    labelOptions = leaflet::labelOptions(style = list("color" = "black","font-size" = "20px")),
                                    popupProperty = htmlwidgets::JS(paste0('function(feature){var props = feature.properties; return \"',
                                                                           '<b>Land Ownership or Jurisdiction:</b> \"+props.DMA_RP+\"',
                                                                           '<br>\"+props.DMA_RP_Cl+\"',
                                                                           '<br><b>HUC12:</b> \"+props.HUC12+\"',
                                                                           '<br><b>Version:</b> \"+props.Version+\"',
                                                                           ' \"}')))



length(subbasin_huc8)
length(subbasin_huc8_lower)
where_huc8_lower
length(subbasin_huc8_middle)
where_huc8_middle
length(subbasin_huc8_southern)
where_huc8_southern
length(subbasin_huc12)
where_huc12_1
where_huc12_2
where_huc12_3
where_huc12_4
where_huc12_5
where_huc12_6
where_huc12_7

labelOptions = leaflet::labelOptions(offset = c(0,0),
                                     opacity = 1,
                                     textsize = "12px",
                                     sticky = TRUE),
popupOptions = leaflet::popupOptions(maxWidth = 800, maxHeight = 500)) %>% 
  
  
  popupProperty = htmlwidgets::JS(paste0('function(feature){var props = feature.properties; return \"',
                                         '<b>Waterbody Name:</b> \"+props.GNIS_Name+\"',
                                         '<br><b>Temperature Criteria:</b> \"+props.Temperature_Criteria+\"',
                                         '<br><b>Non Spawning 7DADM deg-C:</b> \"+props.Temperature_Criterion_7dADM_C+\"',
                                         '<br><b>Temperature Spawning Dates:</b> \"+props.Temperature_Spawn_dates+\"',
                                         ' \"}'))) %>%